name: Fiware Swarm
description: Fiware Swarm template
stacks:
  - name: fiwarelab-portainer
    templateId: 'fiwarelab-swarm-catalog:infra*fiwarelab-portainer'
  - name: swarm
    templateId: 'community:infra*swarm'
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: ipsec
    templateId: 'library:infra*ipsec'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
